export const DEFAULT_CANONICAL_SPELL_NAMES = [
  "Cause Fear",
  "Magic Dart",
  "Fireball",
  "Apportation",
  "Volatile Blastmotes",
  "Dig",
  "Bolt of Fire",
  "Bolt of Cold",
  "Lightning Bolt",
  "Arcjolt",
  "Plasma Beam",
  "Permafrost Eruption",
  "Blinkbolt",
  "Vhi's Electric Charge",
  "Vhi's Electrolunge",
  "Bolt of Magma",
  "Polymorph",
  "Slow",
  "Haste",
  "Petrify",
  "Confuse",
  "Invisibility",
  "Throw Flame",
  "Throw Frost",
  "Disjunction",
  "Freezing Cloud",
  "Freezing Gust",
  "Mephitic Cloud",
  "Venom Bolt",
  "Olgreb's Toxic Radiance",
  "Teleport Other",
  "Death's Door",
  "Mass Confusion",
  "Smiting",
  "Summon Small Mammal",
  "Abjuration",
  "Bolt of Draining",
  "Lehudib's Crystal Spear",
  "Polar Vortex",
  "Poisonous Cloud",
  "Fire Storm",
  "Call Down Damnation",
  "Call Down Lightning",
  "Blink",
  "Blink Range",
  "Blink Away",
  "Blink Close",
  "Iskenderun's Mystic Blast",
  "Summon Horrible Things",
  "Malign Gateway",
  "Charm",
  "Animate Dead",
  "Pain",
  "Soul Splinter",
  "Vampiric Draining",
  "Haunt",
  "Martyr's Knell",
  "Borgnjor's Revivification",
  "Freeze",
  "Ozocubu's Refrigeration",
  "Sticky Flame",
  "Summon Ice Beast",
  "Ozocubu's Armour",
  "Call Imp",
  "Deflect Missiles",
  "Berserker Rage",
  "Dispel Undead",
  "Poison Arrow",
  "Banishment",
  "Sting",
  "Sublimation of Blood",
  "Tukima's Dance",
  "Summon Demon",
  "Summon Greater Demon",
  "Cigotuvi's Putrefaction",
  "Iron Shot",
  "Bombard",
  "Stone Arrow",
  "Shock",
  "Swiftness",
  "Debugging Ray",
  "Agonising Touch",
  "Curse of Agony",
  "Mindburst",
  "Death Channel",
  "Symbol of Torment",
  "Siphon Essence",
  "Throw Icicle",
  "Airstrike",
  "Momentum Strike",
  "Shadow Creatures",
  "Confusing Touch",
  "Passwall",
  "Ignite Poison",
  "Call Canine Familiar",
  "Summon Dragon",
  "Ensorcelled Hibernation",
  "Metabolic Englaciation",
  "Silence",
  "Shatter",
  "Dispersal",
  "Static Discharge",
  "Corona",
  "Alistair's Intoxication",
  "Lee's Rapid Deconstruction",
  "Sandblast",
  "Sculpt Simulacrum",
  "Conjure Ball Lightning",
  "Chain Lightning",
  "Portal Projectile",
  "Monstrous Menagerie",
  "Passage of Golubria",
  "Fulminant Prism",
  "Paralyse",
  "Minor Healing",
  "Major Healing",
  "Woodweal",
  "Hurl Damnation",
  "Brain Bite",
  "Noxious Cloud",
  "Steam Ball",
  "Ufetubi Swarm",
  "Summon Sin Beast",
  "Bolt of Devastation",
  "Spit Poison",
  "Summon Undead",
  "Cantrip",
  "Quicksilver Bolt",
  "Metal Splinters",
  "Splinterspray",
  "Miasma Breath",
  "Summon Drakes",
  "Blink Other",
  "Blink Other Close",
  "Summon Mushrooms",
  "Spit Acid",
  "Caustic Breath",
  "Pyre Arrow",
  "Fire Breath",
  "Searing Breath",
  "Chaos Breath",
  "Cold Breath",
  "Glacial Breath",
  "Summon Water Elementals",
  "Porkalator",
  "Spawn Tentacles",
  "Summon Eyeballs",
  "Haste Other",
  "Summon Earth Elementals",
  "Summon Air Elementals",
  "Summon Fire Elementals",
  "Sleep",
  "Mara Summon",
  "Summon Illusion",
  "Primal Wave",
  "Call Tide",
  "Orb of Destruction",
  "Ink Cloud",
  "Might",
  "Might Other",
  "Awaken Forest",
  "Druid's Call",
  "Brothers in Arms",
  "Trog's Hand",
  "Summon Mortal Champion",
  "Vanquished Vanguard",
  "Summon Holies",
  "Heal Other",
  "Holy Flames",
  "Holy Breath",
  "Injury Mirror",
  "Drain Life",
  "Leda's Liquefaction",
  "Summon Hydra",
  "Mesmerise",
  "Hellfire Court",
  "Petrifying Cloud",
  "Inner Flame",
  "Ensnare",
  "Greater Ensnare",
  "Thunderbolt",
  "Iskenderun's Battlesphere",
  "Summon Minor Demon",
  "Sticks to Snakes",
  "Malmutate",
  "Gloom",
  "Beckoning Gale",
  "Force Lance",
  "Sentinel's Mark",
  "Word of Recall",
  "Injury Bond",
  "Spectral Cloud",
  "Ghostly Fireball",
  "Call Lost Souls",
  "Dimension Anchor",
  "Blink Allies Encircling",
  "Awaken Vines",
  "Volley of Thorns",
  "Cage of Brambles",
  "Waterstrike",
  "Wind Blast",
  "Strip Willpower",
  "Fugue of the Fallen",
  "Summon Vermin",
  "Malign Offering",
  "Searing Ray",
  "Discord",
  "Invisibility Other",
  "Virulence",
  "Orb of Electricity",
  "Flash Freeze",
  "Creeping Frost",
  "Legendary Destruction",
  "Forceful Invitation",
  "Plane Rend",
  "Chain of Chaos",
  "Call of Chaos",
  "Sign of Ruin",
  "Sap Magic",
  "Major Destruction",
  "Blink Allies Away",
  "Summon Forest",
  "Forge Lightning Spire",
  "Forge Blazeheart Golem",
  "Rebounding Blaze",
  "Rebounding Chill",
  "Glaciate",
  "Dragon's Call",
  "Spellspark Servitor",
  "Summon Mana Viper",
  "Phantom Mirror",
  "Diminish Spells",
  "Corrosive Bolt",
  "Bolt of Light",
  "Bolt of Flesh",
  "Awaken Flesh",
  "gehenna serpent of hell breath",
  "cocytus serpent of hell breath",
  "dis serpent of hell breath",
  "tartarus serpent of hell breath",
  "Summon Emperor Scorpions",
  "Irradiate",
  "Spit Lava",
  "Electrical Bolt",
  "Flaming Cloud",
  "Throw Barbs",
  "Battlecry",
  "Warning Cry",
  "Hunting Call",
  "Funeral Dirge",
  "Seal Doors",
  "Flay",
  "Berserk Other",
  "Corrupting Pulse",
  "Siren Song",
  "Avatar Song",
  "Paralysis Gaze",
  "Confusion Gaze",
  "Antimagic Gaze",
  "Draining Gaze",
  "Weakening Gaze",
  "Mourning Wail",
  "Death Rattle",
  "March of Sorrows",
  "Summon Scarabs",
  "Throw Ally",
  "Cleansing Flame",
  "Gell's Gravitas",
  "Yara's Violent Unravelling",
  "Entropic Weave",
  "Summon Executioners",
  "Oblivion Howl",
  "Prayer of Brilliance",
  "Iceblast",
  "Slug Dart",
  "Fleetfoot",
  "Infernal Servant",
  "Bind Souls",
  "Infestation",
  "Still Winds",
  "Resonance Strike",
  "Ghostly Sacrifice",
  "Dream Dust",
  "Lesser Beckoning",
  "Upheaval",
  "Mercury Arrow",
  "Poisonous Vapours",
  "Ignition",
  "Borgnjor's Vile Clutch",
  "Fastroot",
  "Warp Space",
  "Sojourning Bolt",
  "Harpoon Shot",
  "Grasping Roots",
  "Throw Bolas",
  "Throw Klown Pie",
  "Sporulate",
  "Launch Sporangium",
  "Starburst",
  "Foxfire",
  "Marshlight",
  "Hailstorm",
  "Eringya's Noxious Bog",
  "Agony",
  "Dispel Undead Range",
  "Frozen Ramparts",
  "Maxwell's Capacitive Coupling",
  "Sonic wave",
  "Roll",
  "Hurl Sludge",
  "Summon Tzitzimitl",
  "Summon Hell Sentinel",
  "Awaken Armour",
  "Manifold Assault",
  "Concentrate Venom",
  "Eruption",
  "Pyroclastic Surge",
  "Stunning Burst",
  "Corrupt",
  "Conjure Living Spells",
  "Summon Cactus Giant",
  "Stoke Flames",
  "Seracfall",
  "Scorch",
  "Flame Wave",
  "Enfeeble",
  "Summon Spiders",
  "Anguish",
  "Summon Scorpions",
  "Sheza's Dance",
  "Divine Armament",
  "Kiss of Death",
  "Jinxbite",
  "Sigil of Binding",
  "Dimensional Bullseye",
  "Brom's Barrelling Boulder",
  "Vitrify",
  "Vitrifying Gaze",
  "Crystallising Shot",
  "Tremorstone",
  "Regenerate Other",
  "Mass Regeneration",
  "Noxious Breath",
  "Unleash Destruction",
  "Hurl Torchlight",
  "Combustion Breath",
  "Nullifying Breath",
  "Steam Breath",
  "Mud Breath",
  "Galvanic Breath",
  "Maxwell's Portable Piledriver",
  "Gell's Gavotte",
  "Magnavolt",
  "Fulsome Fusillade",
  "Rimeblight",
  "Hoarfrost Cannonade",
  "Seismic Stomp",
  "Hoarfrost Bullet",
  "Flashing Balestra",
  "Phantom Blitz",
  "Bestow Arms",
  "Hellfire Mortar",
  "Shadow Shard",
  "Shadow Beam",
  "Shadowball",
  "Creeping Shadow",
  "Shadow Tempest",
  "Shadow Prism",
  "Shadow Puppet",
  "Shadow Turret",
  "Shadow Shot",
  "Shadow Bind",
  "Shadow Torpor",
  "Shadow Draining",
  "Grave Claw",
  "Launch Clockwork Bee",
  "Construct Spike Launcher",
  "Kinetic Grapnel",
  "Diamond Sawblades",
  "Shred",
  "Eringya's Surprising Crocodile",
  "Platinum Paragon",
  "Alistair's Walking Alembic",
  "Forge Monarch Bomb",
  "Launch Bomblet",
  "Splinterfrost Shell",
  "Nazja's Percussive Tempering",
  "Nazja's All-Purpose Tempering",
  "Fortress Blast",
  "Summon Seismosaurus Egg",
  "Forge Phalanx Beetle",
  "Rending Blade",
  "Magma Barrage",
  "Vex",
  "Ravenous Swarm",
  "Dominate Undead",
  "Detonation Catalyst",
  "Rust Breath",
  "Golden Breath",
  "Sphinx Sisters",
  "Ill Omen",
  "Doom Bolt",
  "Warp Body",
  "Ostracise",
  "Mutagenic Gaze",
  "Acid Ball",
  "nonexistent spell",
  "Pyrrhic Recollection",
  "Planar Overlay",
  "Doomsaying",
  "Sleetstrike",
  "Landbreaker",
  "Aura of Abjuration",
  "Bolt of Inaccuracy",
  "Chant Fire Storm",
  "Cigotuvi's Degeneration",
  "Cigotuvi's Embrace",
  "Condensation Shield",
  "Controlled Blink",
  "Control Teleport",
  "Control Undead",
  "Control Winds",
  "Corrupt Body",
  "Cure Poison",
  "Darkness",
  "Old Deflect Missiles",
  "Delayed Fireball",
  "Demonic Horde",
  "Draconian Breath",
  "Ephemeral Infusion",
  "Evaporate",
  "Explosive Bolt",
  "Rakshasa Summon",
  "Fire Brand",
  "Flight",
  "Forceful Dismissal",
  "Freezing Aura",
  "Frenzy",
  "Fulsome Distillation",
  "Grand Avatar",
  "Haste Plants",
  "Holy Light",
  "Hunting Cry",
  "Localized Ignite Poison",
  "Insulation",
  "Infusion",
  "Summon Iron Elementals",
  "Lethal Infusion",
  "Melee",
  "Mislead",
  "Phase Shift",
  "Poison Weapon",
  "Random Bolt",
  "Rearrange the Pieces",
  "Recall",
  "Regeneration",
  "Ring of Flames",
  "See Invisible",
  "Shaft Self",
  "Shroud of Golubria",
  "Silver Blast",
  "Singularity",
  "Song of Shielding",
  "Spectral Weapon",
  "Stoneskin",
  "Summon Butterflies",
  "Summon Elemental",
  "Summon Rakshasa",
  "Summon Twister",
  "Sunray",
  "Sure Blade",
  "Throw",
  "Vampire Summon",
  "Warp Weapon",
  "Weave Shadows",
  "Striking",
  "Resurrect",
  "Holy word",
  "Sacrifice",
  "Miasma cloud",
  "Poison cloud",
  "Fire cloud",
  "Steam cloud",
  "Homunculus",
  "Old serpent of hell breath",
  "Scattershot",
  "Summon swarm",
  "Cloud Cone",
  "Ring of Thunder",
  "Twisted Resurrection",
  "Random Effects",
  "Hydra Form",
  "Vortex",
  "Goad Beasts",
  "Teleport Self",
  "Tomb of Doroklohe",
  "Excruciating Wounds",
  "Conjure Flame",
  "Corpse Rot",
  "Flame Tongue",
  "Beastly Appendage",
  "Spider Form",
  "Ice Form",
  "Blade Hands",
  "Statue Form",
  "Storm Form",
  "Dragon Form",
  "Necromutation",
  "Awaken Earth",
  "Animate Skeleton",
  "Drain Magic",
] as const
